apiVersion: v2
name: kgh
description: A lightweight GitOps controller for Kubernetes homelab clusters
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - gitops
  - kubernetes
  - homelab
  - automation
  - cd
home: https://github.com/Taiwrash/k8s-gitops
maintainers:
  - name: Taiwrash
    email: your-email@example.com
